### ISSUE TITLE
Could you please add an "Instant Start" Feature (for XCOM: Chimera Squad)?

### ISSUE THREAD

**Issue by pandavova** [X2CommunityCore/xcom2-launcher#197]
That should be a really easy thing to do, I just want to start the game without any Launchers (and with the Steam Overlay for the Playtime Tracking and Achievments).
The ""xcom.exe location path" %command%" thing doesn't really work in the Steam-Startoptions so that would be a nice workaround.

**Comment by RevZero** [comment]
I do not understand what you are asking. Please be specific. Playtime is tracked just fine when using AML. What do you mean with "I just want to start the game without any Launchers"? AML is a launcher.

**Comment by pandavova** [comment]
Ok, let me try to be more clear:
Currently if you launch XCOM:CS through Steam normaly it launches the weird launcher and then you need to press play on that launcher and only then the game starts.
If you use AML its the same but the launcher isn't bad.

If you launch XCOM:CS through the "xcom.exe" the game starts instantly but not in Steam.

A nice feature would be an option that the game would start without the AML interface and only launch the AML interface if you are holding a key or something like that.

**Comment by RevZero** [comment]
Sorry, but I think that is somewhat too specific and there would be more work involved that you may think. 
Furthermore, AML is supposed to update/verify all mods to make sure that it doesn't try to use mods that have already been uninstalled for example.
Keeping that as it is, essentially the only benefit would be that you do not have to press the "run game" button. And since implementing the stuff takes more time that pressing the a few hundred times, it is just not worth the effort.

**Comment by pandavova** [comment]
Ok, thats fine!
