### ISSUE TITLE
Latest Launcher update

### ISSUE THREAD

**Issue by AZdave66** [X2CommunityCore/xcom2-launcher#219]
I noticed that the new launcher doesn't show the load order filter or the ability to change the load order of the mods.  Am I missing it somehow?  That function was extremely helpful in getting my mods to load correctly and my game not to crash.  Was it removed? If not what am I doing wrong?

Thank you for your great work!

**Comment by Iridar** [comment]
Right click on the columns header line and there you can toggle visible columns. 

https://imgur.com/wqbfHgu

**Comment by RevZero** [comment]
The order column is now hidden by default, because it does not necessary represent the "real" loader order. There are other factors like subscription order that (seem) to influence how XCOM loads mods. There were some discussions about this on discord, but nothing really conclusive AFAIK.

[For some mod list tips see also](https://github.com/X2CommunityCore/xcom2-launcher/wiki/Basic-usage#modlist)
