### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by KnowChillx** [X2CommunityCore/xcom2-launcher#248]
![Screen Shot 2021-01-05 at 12 51 24 AM](https://user-images.githubusercontent.com/76963390/103559469-25037300-4ef1-11eb-9ffb-47e5d0d4535e.png)
![Screen Shot 2021-01-05 at 12 51 31 AM](https://user-images.githubusercontent.com/76963390/103559485-2a60bd80-4ef1-11eb-8214-0637570f1986.png)
![Screen Shot 2021-01-05 at 12 51 38 AM](https://user-images.githubusercontent.com/76963390/103559489-2c2a8100-4ef1-11eb-8930-877fa8ac75cc.png)
![Screen Shot 2021-01-05 at 12 51 54 AM](https://user-images.githubusercontent.com/76963390/103559494-2df44480-4ef1-11eb-9797-89a9d9d4e084.png)

Not sure why its asking me what language I want to use but the result is just the creation of some giberrish language file.

**Comment by robojumper** [comment]
I assume what's happening is that your OS is trying to open the .NET executable as an archive (because PE executables, `.exe`, are archives). AML doesn't officially support MacOS, because it's tied to Steam and only ships a `steam_api64.dll` for Windows 64-bit.

Folks have had success with Wine for Linux in #171, maybe Wine can be a workaround here too.

@RevZero Does it make sense to keep this issue open for MacOS support?

**Comment by RevZero** [comment]
@robojumper I will close this. I do not think there is much demand to run AML on Mac OS and it will "never" be natively  supported. If there is a known workaround to run AML on MacOS, it should probably just go to the FAQ.
