### ISSUE TITLE
Sort by subscribed items.

### ISSUE THREAD

**Issue by Thehail** [X2CommunityCore/xcom2-launcher#316]
**Description**
Allow to sort by subscribed items. Sometimes I just subscribe to a new collection in the workshop, and don't want to bother verifying files so it can download the mods again. This way, I can just unsubscribe and keep the mods downloaded and subscribe to a new collection.

**Suggest a solution**
Add subscribed sorting option.

**Comment by Iridar** [comment]
When you unsubscribe from a workshop mod, steam automatically deletes it.

**Comment by RevZero** [comment]
The new "Unsubscribe" feature does exactly that, "Unsubscribe" the mod from Steam. As Iridar pointed out, Steam then deletes the data automatically.
Its just a usability feature. Instead of 

1. opening Steam
2. searching and unsubscribing the desired mod(s)
3. update mod list in AML

you now just have to 
1. select mods in AML and "unsubscribe"
