### ISSUE TITLE
Delete/Unsubscribe severe issue

### ISSUE THREAD

**Issue by deblueseven** [X2CommunityCore/xcom2-launcher#35]
Apparently using that option prevents said mod from EVER be used again in this launcher. At least it simply wont ever show up no matter the fact that I have the mod subscribed to. The mod is "Character Pool Uniforms".

I REALLY want to have it fixed so I can use it again. Reason I even used that option was because I wanted it to "reset" by deleting it and unsubscribing then resubbing and checking it in the launcher.

**Comment by boycad** [comment]
Pardon my chiming in, but that sounds serious. I have, maybe related, problems with the launcher as well. I can't use it. They are not your exact problems, but it seems to make permanent and irreversible changes to the installed state of the game.  I hope I'm not wrong. I'm just a user, and it seemed to...I like the project‎ though. Regards,~boycad                                                                                                                                                                                                                                                                                                                                        ~mb                                                                                                                                                                                                                From: debluesevenSent: Friday, December 22, 2017 4:43 PMTo: X2CommunityCore/xcom2-launcherReply To: X2CommunityCore/xcom2-launcherCc: SubscribedSubject: [X2CommunityCore/xcom2-launcher] Delete/Unsubscribe severe issue (#35)Apparently using that option prevents said mod from EVER be used again in this launcher. At least it simply wont ever show up no matter the fact that I have the mod subscribed to. The mod is "Character Pool Uniforms".
I REALLY want to have it fixed so I can use it again. Reason I even used that option was because I wanted it to "reset" by deleting it and unsubscribing then resubbing and checking it in the launcher.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/X2CommunityCore/xcom2-launcher","title":"X2CommunityCore/xcom2-launcher","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/X2CommunityCore/xcom2-launcher"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Delete/Unsubscribe severe issue (#35)"}],"action":{"name":"View Issue","url":"https://github.com/X2CommunityCore/xcom2-launcher/issues/35"}}}

**Comment by BTernaryTau** [comment]
I'm unable to reproduce this issue. Can you confirm the mod has actually been downloaded when the launcher isn't showing it?

**Comment by deblueseven** [comment]
Well I'm not sure what you mean by that, I am certainly 100% sure that I am subscribed to it. Lie other workshop games, say Left 4 Dead and 2 I can unsubcribe and then resubscribe to get back the content so I figured Xcom 2 was the same. 

Although to be fair this launcher is great and all but for some reason unsubcribing from the workshop doesn't really take effect on the mod launcher, after a while sometimes and other times after quiet a long while so my guess is the mod I'm asking about is maybe stuck in a limbo between being deleted and so can't get new data until it has be deleted... Just a guess of course.

**Comment by BTernaryTau** [comment]
I mean go to your workshop folder and confirm that Steam has actually downloaded the files for the mod, then open the launcher and make sure it still isn't showing up. Steam doesn't always download the files immediately after you subscribe to a mod.

**Comment by deblueseven** [comment]
I searched for "pool" and "uniform" within XCOM 2 workshop content and no it does not actually appear which in other word means it is not downloaded. Thanks for helping me clearing that up but now I really want to have it downloaded. How would I do this? I am subscribed for 2 days now after all.

**Comment by BTernaryTau** [comment]
Try unsubscribing and resubscribing I guess.

**Comment by deblueseven** [comment]
Well it "magically" works now, but I can't spot the issue. I did validate the game and let the config folder rebuild itself so maybe something there but even then it didn't work but somehow now it does. It is also possible that some kind of update was holding the mod from being downloaded idk. Thanks for the support man.

**Comment by BTernaryTau** [comment]
No problem.
