### ISSUE TITLE
Renaming mods 

### ISSUE THREAD

**Issue by dotechin** [X2CommunityCore/xcom2-launcher#45]
Hello there, when I rename and tidy up my mods list it goes back to the original names and IDs as soon as I close and relaunch the app. I already tried to save and it seems not to work.

**Comment by Dragon-32** [comment]
Little late... I'm pretty sure that mod names are pulled from Steam Workshop, so that's why changes are overwritten. The only mods you can name freely would be those without a Workshop entry

**Comment by RevZero** [comment]
Looking at the code, AML is supposed to "remember" that the mod was named manually and prevent overwriting the custom name during workshop update. I will look unto it.

**Comment by RevZero** [comment]
I looked into this. When just changing the mod name there isn't and wasn't (for the last few older versions I checked) a problem. 

However, OP said that "it goes back to the original names and IDs". So he did not only change the mod name, but also the ID. To rename the ID, he had to use the "Mod Info -> Inspect" tab. Doing that, I can reproduce the issue.

Since the ID shouldn't be changed anyway it was already changes to read-only (as in #78), so this can be closed.
