### ISSUE TITLE
WOTC crashes on start-up

### ISSUE THREAD

**Issue by richierich89** [X2CommunityCore/xcom2-launcher#48]
Hi there,

War of the chosen crashes on start-up for me, it loads the window for about 5 seconds then it disappears. Happens with mods and no mods selected

**Comment by Dragon-32** [comment]
Does it happen when you use the Firaxis launcher? If so, it's not a problem caused by the Community Launcher

**Comment by richierich89** [comment]
No, it's from the launcher on here, No conflicts detected with the mod

**Comment by boycad** [comment]
Excuse me for asking, richierrich89, but to troubleshoot requires clear answers. Does the game launch when you use the Firaxis launcher in the install directory?                                                                                                                                                                                                                                                                                                                                        ~bc                                                                                                                                                                                                                From: richierich89Sent: Saturday, July 14, 2018 12:44 PMTo: X2CommunityCore/xcom2-launcherReply To: X2CommunityCore/xcom2-launcherCc: SubscribedSubject: Re: [X2CommunityCore/xcom2-launcher] WOTC crashes on start-up (#48)No, it's from the launcher on here, No conflicts detected with the mod

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/X2CommunityCore/xcom2-launcher","title":"X2CommunityCore/xcom2-launcher","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/X2CommunityCore/xcom2-launcher"}},"updates":{"snippets":[{"icon":"PERSON","message":"@richierich89 in #48: No, it's from the launcher on here, No conflicts detected with the mod"}],"action":{"name":"View Issue","url":"https://github.com/X2CommunityCore/xcom2-launcher/issues/48#issuecomment-405045501"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/X2CommunityCore/xcom2-launcher/issues/48#issuecomment-405045501",
"url": "https://github.com/X2CommunityCore/xcom2-launcher/issues/48#issuecomment-405045501",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [X2CommunityCore/xcom2-launcher] WOTC crashes on start-up (#48)",
"sections": [
{
"text": "",
"activityTitle": "**richierich89**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@richierich89",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"X2CommunityCore/xcom2-launcher\",\n\"issueId\": 48,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"X2CommunityCore/xcom2-launcher\",\n\"issueId\": 48\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/X2CommunityCore/xcom2-launcher/issues/48#issuecomment-405045501"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356461074\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by richierich89** [comment]
Yes, the game launches properly on the firaxis launcher. Think I've got it solved now though, there was a problem with a mod which had a recent update which on uninstall seems to work.

Thanks for looking and sorry for bothering you

**Comment by Dragon-32** [comment]
OK, cool
