### ISSUE TITLE
Mod ID comparison is case sensitive

### ISSUE THREAD

**Issue by Cylindryk** [X2CommunityCore/xcom2-launcher#94]
Hello.
Recently I have a little problem, which turned is a problem with 2 mods having same mod ID, but one had ID "M96MATTOCK" and second "M96Mattock".
For Mod Launcher (newest version), it was not duplicate, as it wasn't showing any "duplicate id error", but for game it was - one other mod was trying to do something with this, game instead would crash at the start.

Is there any option to prevent this kind of situation in future?

**Comment by RevZero** [comment]
Mod ID comparisons are currently indeed case sensitive. As XCOM doesn't differentiate, I guess we should change this.

/cc @Xymanek 

PS
The mod code related to marking duplicates while importing mods is a mess. I would be happy to clean it up. From having a brief look at the code we have
* a "isDupe" check that can never be true 
* a mark duplicates loop that is never executed because of "isDupe" never being true
* a separate MarkDuplicates() function that finally marks duplicates after the import is finished
